In [2]:
#CREATED BINS LIKE  [Young, Adult, and Senior]


import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# DATASET
df = pd.read_csv(r"C:\Users\nh013\Desktop\bank churn dataset\Customer-Churn-Records.csv")

# CALCULATE THE EXITED RATE
exited_rate = df['Exited'].sum() / df.shape[0]
print("Exited Rate:", exited_rate)

# USING FUNCTION TO HANDLE_OUTLIERS
def handle_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5*IQR
    upper_bound = Q3 + 1.5*IQR
    df = df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]
    return df

# FEATURE ENGINEERING - AGE BINNING
bins = [0, 30, 60, 100]
labels = ['Young', 'Adult', 'Senior']
df['AgeGroup'] = pd.cut(df['Age'], bins=bins, labels=labels)

# FEATURE SELECT
df_selected = df[['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited', 'Complain', 'Satisfaction Score', 'Card Type']]

# IDENTIFYING MISSING VALUES
print(df.isnull().sum())

# DROP ROWS WITH MISSING VALUES
df.dropna(inplace=True)

# FILL MISSING VALUES WITH MEAN
mean = df.mean()
df.fillna(mean, inplace=True)

# FILL MISSING VALUES WITH MODE
mode = df.mode().iloc[0]
df.fillna(mode, inplace=True)

# FILL MISSING VALUES WITH FORWARD FILL
df.fillna(method='ffill', inplace=True)

# FILL MISSING VALUES WITH BACKWARD FILL
df.fillna(method='bfill', inplace=True)

# DROP THE GEOGRAPHY COLUMN
df.drop('Geography', axis=1, inplace=True)

# ONE HOT ENCODING
df = pd.get_dummies(df, columns=['Gender', 'AgeGroup'])

# HANDLE OUTLIERS
df = handle_outliers(df, 'Exited')

# REMOVE DUPLICATE ROWS
df.drop_duplicates(inplace=True)

# NORMALIZE AND SCALE ALL NUMERICAL COLUMNS
scaler = MinMaxScaler()
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = scaler.fit_transform(df[num_cols])

scaler = StandardScaler()
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = scaler.fit_transform(df[num_cols])

print(df)

Exited Rate: 0.2038
RowNumber             0
CustomerId            0
Surname               0
CreditScore           0
Geography             0
Gender                0
Age                   0
Tenure                0
Balance               0
NumOfProducts         0
HasCrCard             0
IsActiveMember        0
EstimatedSalary       0
Exited                0
Complain              0
Satisfaction Score    0
Card Type             0
Point Earned          0
AgeGroup              0
dtype: int64

C:\Users\nh013\AppData\Local\Temp\ipykernel_9136\2472707339.py:36: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  mean = df.mean()
C:\Users\nh013\AppData\Local\Temp\ipykernel_9136\2472707339.py:41: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.fillna(mode, inplace=True)

      RowNumber  CustomerId    Surname  CreditScore       Age    Tenure  \
1     -1.737051   -0.611274       Hill    -0.458344  0.354748 -1.400118
3     -1.736359    0.142000       Boni     0.493101  0.157223 -1.400118
4     -1.736013    0.651227   Mitchell     2.071871  0.552273 -1.052934
6     -1.735321   -1.374821   Bartlett     1.779119  1.243609  0.682988
8     -1.734630    1.410550         He    -1.577075  0.651035 -0.358565
...         ...         ...        ...          ...       ...       ...
9993   1.719015   -1.699099     Rahman    -0.081948 -0.929162  0.682988
9994   1.719361    0.392056       Wood     1.549100 -0.830400 -1.052934
9995   1.719706   -1.183893   Obijiaku     1.245892  0.157223 -0.011381
9996   1.720052   -1.690373  Johnstone    -1.420244 -0.237826  1.724541
9999   1.721090   -0.875993     Walker     1.465456 -0.929162 -0.358565

       Balance  NumOfProducts  HasCrCard  IsActiveMember  ...  Exited  \
1     0.176062      -1.068105  -1.553781        0.896097  ...     0.0
3    -1.157446       0.894566  -1.553781       -1.115951  ...     0.0
4     0.839619      -1.068105   0.643591        0.896097  ...     0.0
6    -1.157446       0.894566   0.643591        0.896097  ...     0.0
8     1.102799       0.894566  -1.553781        0.896097  ...     0.0
...        ...            ...        ...             ...  ...     ...
9993  1.309797      -1.068105   0.643591       -1.115951  ...     0.0
9994 -1.157446       0.894566  -1.553781       -1.115951  ...     0.0
9995 -1.157446       0.894566   0.643591       -1.115951  ...     0.0
9996 -0.244610      -1.068105   0.643591        0.896097  ...     0.0
9999  0.913321      -1.068105   0.643591       -1.115951  ...     0.0

       Complain  Satisfaction Score  Card Type Point Earned  Gender_Female  \
1     28.199291           -0.012760    DIAMOND    -0.668108       1.157157
3     -0.035462            1.408142       GOLD    -1.136973       1.157157
4     -0.035462            1.408142       GOLD    -0.805229       1.157157
6     -0.035462           -0.723211     SILVER    -1.773923      -0.864187
8     -0.035462           -0.012760       GOLD    -1.574876      -0.864187
...         ...                 ...        ...          ...            ...
9993  -0.035462            1.408142    DIAMOND     0.477517      -0.864187
9994  -0.035462            0.697691   PLATINUM    -1.309481       1.157157
9995  -0.035462           -1.433662    DIAMOND    -1.358137      -0.864187
9996  -0.035462            1.408142   PLATINUM     0.725220      -0.864187
9999  -0.035462           -0.012760    DIAMOND     1.344477       1.157157

      Gender_Male  AgeGroup_Young  AgeGroup_Adult  AgeGroup_Senior
1       -1.157157       -0.544353        0.611897        -0.214109
3       -1.157157       -0.544353        0.611897        -0.214109
4       -1.157157       -0.544353        0.611897        -0.214109
6        0.864187       -0.544353        0.611897        -0.214109
8        0.864187       -0.544353        0.611897        -0.214109
...           ...             ...             ...              ...
9993     0.864187        1.837043       -1.634263        -0.214109
9994    -1.157157        1.837043       -1.634263        -0.214109
9995     0.864187       -0.544353        0.611897        -0.214109
9996     0.864187       -0.544353        0.611897        -0.214109
9999    -1.157157        1.837043       -1.634263        -0.214109

[7962 rows x 21 columns]

In [4]:
#AGGREGATION FEATURE ENGINEERING


import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# USING FUNCTION TO HANDLE_OUTLIERS
def handle_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5*IQR
    upper_bound = Q3 + 1.5*IQR
    df = df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]
    return df



 
    
# DATASET
df = pd.read_csv(r"C:\Users\nh013\Desktop\bank churn dataset\Customer-Churn-Records.csv")


# FEATURE ENGINEERING - AGGREGATION FEATURES
# CALCULATE THE AVERAGE BALANCE FOR EACH GENDER
df_grouped = df.groupby('Gender')['Balance'].mean()
df_grouped = df_grouped.rename('AvgBalanceByGender')
df = df.merge(df_grouped, on='Gender', how='left')


# FEATURE SELECT
df_selected = df[['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited', 'Complain', 'Satisfaction Score', 'Card Type', 'AvgBalanceByGender']]


# IDENTIFYING MISSING VALUES
print(df.isnull().sum())

# DROP ROWS WITH MISSING VALUES
df.dropna(inplace=True)

# FILL MISSING VALUES WITH MEAN
mean = df.mean()
df.fillna(mean, inplace=True)

# FILL MISSING VALUES WITH MODE
mode = df.mode().iloc[0]
df.fillna(mode, inplace=True)

# FILL MISSING VALUES WITH FORWARD FILL
df.fillna(method='ffill', inplace=True)

# FILL MISSING VALUES WITH BACKWARD FILL
df.fillna(method='bfill', inplace=True)

# DROP THE GEOGRAPHY COLUMN
df.drop('Geography', axis=1, inplace=True)

# ONE HOT ENCODING
df = pd.get_dummies(df, columns=['Gender', 'Age'])

# HANDLE OUTLIERS
df = handle_outliers(df, 'Exited')

# REMOVE DUPLICATE ROWS
df.drop_duplicates(inplace=True)

# NORMALIZE AND SCALE ALL NUMERICAL COLUMNS
scaler = MinMaxScaler()
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = scaler.fit_transform(df[num_cols])

scaler = StandardScaler()
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = scaler.fit_transform(df[num_cols])

print(df)

Exited Rate: 0.2038
RowNumber             0
CustomerId            0
Surname               0
CreditScore           0
Geography             0
Gender                0
Age                   0
Tenure                0
Balance               0
NumOfProducts         0
HasCrCard             0
IsActiveMember        0
EstimatedSalary       0
Exited                0
Complain              0
Satisfaction Score    0
Card Type             0
Point Earned          0
AvgBalanceByGender    0
dtype: int64

C:\Users\nh013\AppData\Local\Temp\ipykernel_9136\2302477631.py:43: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  mean = df.mean()

      RowNumber  CustomerId    Surname  CreditScore    Tenure   Balance  \
1     -1.737051   -0.611274       Hill    -0.458344 -1.400118  0.176062
3     -1.736359    0.142000       Boni     0.493101 -1.400118 -1.157446
4     -1.736013    0.651227   Mitchell     2.071871 -1.052934  0.839619
6     -1.735321   -1.374821   Bartlett     1.779119  0.682988 -1.157446
8     -1.734630    1.410550         He    -1.577075 -0.358565  1.102799
...         ...         ...        ...          ...       ...       ...
9993   1.719015   -1.699099     Rahman    -0.081948  0.682988  1.309797
9994   1.719361    0.392056       Wood     1.549100 -1.052934 -1.157446
9995   1.719706   -1.183893   Obijiaku     1.245892 -0.011381 -1.157446
9996   1.720052   -1.690373  Johnstone    -1.420244  1.724541 -0.244610
9999   1.721090   -0.875993     Walker     1.465456 -0.358565  0.913321

      NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  ...  \
1         -1.068105  -1.553781        0.896097         0.223285  ...
3          0.894566  -1.553781       -1.115951        -0.102798  ...
4         -1.068105   0.643591        0.896097        -0.359653  ...
6          0.894566   0.643591        0.896097        -1.562191  ...
8          0.894566  -1.553781        0.896097        -0.431845  ...
...             ...        ...             ...              ...  ...
9993      -1.068105   0.643591       -1.115951        -1.229126  ...
9994       0.894566  -1.553781       -1.115951         1.185558  ...
9995       0.894566   0.643591       -1.115951        -0.060217  ...
9996      -1.068105   0.643591        0.896097         0.034374  ...
9999      -1.068105   0.643591       -1.115951        -1.072125  ...

        Age_78   Age_79    Age_80   Age_81    Age_82    Age_83    Age_84  \
1    -0.025067 -0.02242 -0.019415 -0.02242 -0.011208 -0.011208 -0.011208
3    -0.025067 -0.02242 -0.019415 -0.02242 -0.011208 -0.011208 -0.011208
4    -0.025067 -0.02242 -0.019415 -0.02242 -0.011208 -0.011208 -0.011208
6    -0.025067 -0.02242 -0.019415 -0.02242 -0.011208 -0.011208 -0.011208
8    -0.025067 -0.02242 -0.019415 -0.02242 -0.011208 -0.011208 -0.011208
...        ...      ...       ...      ...       ...       ...       ...
9993 -0.025067 -0.02242 -0.019415 -0.02242 -0.011208 -0.011208 -0.011208
9994 -0.025067 -0.02242 -0.019415 -0.02242 -0.011208 -0.011208 -0.011208
9995 -0.025067 -0.02242 -0.019415 -0.02242 -0.011208 -0.011208 -0.011208
9996 -0.025067 -0.02242 -0.019415 -0.02242 -0.011208 -0.011208 -0.011208
9999 -0.025067 -0.02242 -0.019415 -0.02242 -0.011208 -0.011208 -0.011208

        Age_85    Age_88    Age_92
1    -0.011208 -0.011208 -0.015851
3    -0.011208 -0.011208 -0.015851
4    -0.011208 -0.011208 -0.015851
6    -0.011208 -0.011208 -0.015851
8    -0.011208 -0.011208 -0.015851
...        ...       ...       ...
9993 -0.011208 -0.011208 -0.015851
9994 -0.011208 -0.011208 -0.015851
9995 -0.011208 -0.011208 -0.015851
9996 -0.011208 -0.011208 -0.015851
9999 -0.011208 -0.011208 -0.015851

[7962 rows x 88 columns]

In [15]:
#PCA FEATURE ENGINEERING

import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder
from sklearn.decomposition import PCA

# USING FUNCTION TO HANDLE_OUTLIERS
def handle_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5*IQR
    upper_bound = Q3 + 1.5*IQR
    df = df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]
    return df

# CALCULATE THE EXITED RATE
df = pd.read_csv(r"C:\Users\nh013\Desktop\bank churn dataset\Customer-Churn-Records.csv")
exited_rate = df['Exited'].sum() / df.shape[0]
print("Exited Rate:", exited_rate)

# FEATURE SELECT
df_selected = df[['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited', 'Complain', 'Satisfaction Score', 'Card Type']]

# IDENTIFYING MISSING VALUES
print(df_selected.isnull().sum())

# DROP ROWS WITH MISSING VALUES
df_selected.dropna(inplace=True)

# FILL MISSING VALUES WITH MEAN
mean = df_selected.mean()
df_selected.fillna(mean, inplace=True)

# FILL MISSING VALUES WITH MODE
mode = df_selected.mode().iloc[0]
df_selected.fillna(mode, inplace=True)

# FILL MISSING VALUES WITH FORWARD FILL
df_selected.fillna(method='ffill', inplace=True)

# FILL MISSING VALUES WITH BACKWARD FILL
df_selected.fillna(method='bfill', inplace=True)

# ONE HOT ENCODING
df_encoded = pd.get_dummies(df_selected, columns=['Card Type', 'Gender'])

# HANDLE OUTLIERS
df_encoded = handle_outliers(df_encoded, 'Exited')

# REMOVE DUPLICATE ROWS
df_encoded.drop_duplicates(inplace=True)

# NORMALIZE AND SCALE ALL NUMERICAL COLUMNS
scaler = MinMaxScaler()
num_cols = df_encoded.select_dtypes(include='number').columns
df_encoded[num_cols] = scaler.fit_transform(df_encoded[num_cols])

scaler = StandardScaler()
num_cols = df_encoded.select_dtypes(include='number').columns
df_encoded[num_cols] = scaler.fit_transform(df_encoded[num_cols])

# PERFORM PCA
pca = PCA(n_components=3)
pca_features = pca.fit_transform(df_encoded.drop('Exited', axis=1))


# COMBINE PCA FEATURES WITH TARGET COLUMN
df_final = pd.DataFrame(pca_features, columns=['PCA_1', 'PCA_2', 'PCA_3'])
df_final['Exited'] = df_encoded['Exited'].fillna(0) 



print(df_final.head())

Exited Rate: 0.2038
CreditScore           0
Gender                0
Age                   0
Tenure                0
Balance               0
NumOfProducts         0
HasCrCard             0
IsActiveMember        0
EstimatedSalary       0
Exited                0
Complain              0
Satisfaction Score    0
Card Type             0
dtype: int64
      PCA_1     PCA_2     PCA_3  Exited
0  1.809610 -2.179040  0.078462     NaN
1  1.575697  0.796585  0.082581     0.0
2  1.328980 -1.704666  0.008503     NaN
3 -1.063674  2.028795 -1.330313     0.0
4 -1.438414 -0.433544  0.280462     0.0

C:\Users\nh013\AppData\Local\Temp\ipykernel_9136\3884315974.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected.dropna(inplace=True)
C:\Users\nh013\AppData\Local\Temp\ipykernel_9136\3884315974.py:32: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  mean = df_selected.mean()
C:\Users\nh013\AppData\Local\Temp\ipykernel_9136\3884315974.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected.fillna(mean, inplace=True)
C:\Users\nh013\AppData\Local\Temp\ipykernel_9136\3884315974.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected.fillna(mode, inplace=True)
C:\Users\nh013\AppData\Local\Temp\ipykernel_9136\3884315974.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected.fillna(method='ffill', inplace=True)
C:\Users\nh013\AppData\Local\Temp\ipykernel_9136\3884315974.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected.fillna(method='bfill', inplace=True)

In [18]:
# ROLLING STATISTICS FEATURE ENGINEERING

import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# USING FUNCTION TO HANDLE_OUTLIERS
def handle_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5*IQR
    upper_bound = Q3 + 1.5*IQR
    df = df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]
    return df

 
# DATASET
df = pd.read_csv(r"C:\Users\nh013\Desktop\bank churn dataset\Customer-Churn-Records.csv")

# FEATURE SELECT
df_selected = df[['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited', 'Complain', 'Satisfaction Score', 'Card Type']]

# IDENTIFY MISSING VALUES
print(df.isnull().sum())

# DROP ROWS WITH MISSING VALUES
df.dropna(inplace=True)

# FILL MISSING VALUES WITH MEAN
mean = df.mean()
df.fillna(mean, inplace=True)

# FILL MISSING VALUES WITH MODE
mode = df.mode().iloc[0]
df.fillna(mode, inplace=True)

# FILL MISSING VALUES WITH FORWARD FILL
df.fillna(method='ffill', inplace=True)

# FILL MISSING VALUES WITH BACKWARD FILL
df.fillna(method='bfill', inplace=True)

# DROP THE GEOGRAPHY COLUMN
df.drop('Geography', axis=1, inplace=True)

# ONE HOT ENCODING
df = pd.get_dummies(df, columns=['Gender'])

# HANDLE OUTLIERS
df = handle_outliers(df, 'Exited')

# REMOVE DUPLICATE ROWS
df.drop_duplicates(inplace=True)

# NORMALIZE AND SCALE ALL NUMERICAL COLUMNS
scaler = MinMaxScaler()
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = scaler.fit_transform(df[num_cols])

scaler = StandardScaler()
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = scaler.fit_transform(df[num_cols])


# ADD ROLLING MEAN AND STANDARD DEVIATION FEATURES
rolling_cols = ['CreditScore', 'Age', 'Balance']
window_size = 3

# Compute rolling mean and standard deviation for selected columns
for col in rolling_cols:
    df[f'{col}_rolling_mean'] = df[col].rolling(window=window_size).mean().fillna(0)
    df[f'{col}_rolling_std'] = df[col].rolling(window=window_size).std().fillna(0)

print(df.head())


print(df.head())

Exited Rate: 0.0
RowNumber             0
CustomerId            0
Surname               0
CreditScore           0
Geography             0
Gender                0
Age                   0
Tenure                0
Balance               0
NumOfProducts         0
HasCrCard             0
IsActiveMember        0
EstimatedSalary       0
Exited                0
Complain              0
Satisfaction Score    0
Card Type             0
Point Earned          0
dtype: int64

C:\Users\nh013\AppData\Local\Temp\ipykernel_9136\3016524867.py:33: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  mean = df.mean()

   RowNumber  CustomerId   Surname  CreditScore       Age    Tenure   Balance  \
1  -1.737051   -0.611274      Hill    -0.458344  0.354748 -1.400118  0.176062
3  -1.736359    0.142000      Boni     0.493101  0.157223 -1.400118 -1.157446
4  -1.736013    0.651227  Mitchell     2.071871  0.552273 -1.052934  0.839619
6  -1.735321   -1.374821  Bartlett     1.779119  1.243609  0.682988 -1.157446
8  -1.734630    1.410550        He    -1.577075  0.651035 -0.358565  1.102799

   NumOfProducts  HasCrCard  IsActiveMember  ...  Card Type  Point Earned  \
1      -1.068105  -1.553781        0.896097  ...    DIAMOND     -0.668108
3       0.894566  -1.553781       -1.115951  ...       GOLD     -1.136973
4      -1.068105   0.643591        0.896097  ...       GOLD     -0.805229
6       0.894566   0.643591        0.896097  ...     SILVER     -1.773923
8       0.894566  -1.553781        0.896097  ...       GOLD     -1.574876

   Gender_Female  Gender_Male CreditScore_rolling_mean  \
1       1.157157    -1.157157                 0.000000
3       1.157157    -1.157157                 0.000000
4       1.157157    -1.157157                 0.702209
6      -0.864187     0.864187                 1.448030
8      -0.864187     0.864187                 0.757972

   CreditScore_rolling_std  Age_rolling_mean  Age_rolling_std  \
1                 0.000000          0.000000         0.000000
3                 0.000000          0.000000         0.000000
4                 1.278003          0.354748         0.197525
6                 0.839848          0.651035         0.549885
8                 2.027501          0.815639         0.373908

   Balance_rolling_mean  Balance_rolling_std
1              0.000000             0.000000
3              0.000000             0.000000
4             -0.047255             1.017089
6             -0.491758             1.153006
8              0.261657             1.236005

[5 rows x 24 columns]
   RowNumber  CustomerId   Surname  CreditScore       Age    Tenure   Balance  \
1  -1.737051   -0.611274      Hill    -0.458344  0.354748 -1.400118  0.176062
3  -1.736359    0.142000      Boni     0.493101  0.157223 -1.400118 -1.157446
4  -1.736013    0.651227  Mitchell     2.071871  0.552273 -1.052934  0.839619
6  -1.735321   -1.374821  Bartlett     1.779119  1.243609  0.682988 -1.157446
8  -1.734630    1.410550        He    -1.577075  0.651035 -0.358565  1.102799

   NumOfProducts  HasCrCard  IsActiveMember  ...  Card Type  Point Earned  \
1      -1.068105  -1.553781        0.896097  ...    DIAMOND     -0.668108
3       0.894566  -1.553781       -1.115951  ...       GOLD     -1.136973
4      -1.068105   0.643591        0.896097  ...       GOLD     -0.805229
6       0.894566   0.643591        0.896097  ...     SILVER     -1.773923
8       0.894566  -1.553781        0.896097  ...       GOLD     -1.574876

   Gender_Female  Gender_Male CreditScore_rolling_mean  \
1       1.157157    -1.157157                 0.000000
3       1.157157    -1.157157                 0.000000
4       1.157157    -1.157157                 0.702209
6      -0.864187     0.864187                 1.448030
8      -0.864187     0.864187                 0.757972

   CreditScore_rolling_std  Age_rolling_mean  Age_rolling_std  \
1                 0.000000          0.000000         0.000000
3                 0.000000          0.000000         0.000000
4                 1.278003          0.354748         0.197525
6                 0.839848          0.651035         0.549885
8                 2.027501          0.815639         0.373908

   Balance_rolling_mean  Balance_rolling_std
1              0.000000             0.000000
3              0.000000             0.000000
4             -0.047255             1.017089
6             -0.491758             1.153006
8              0.261657             1.236005

[5 rows x 24 columns]